### ISSUE TITLE
Crop description length in cards, highlight block created from feed block

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar#327]
<img width="922" alt="image" src="https://github.com/hlxsites/sunstar/assets/1191451/65e5241c-4363-4494-baf7-fae60ba86098">

As can be seen above, the description is very long and occupies a lot of space. It needs to be cropped to a fixed length.

**Comment by meejain** [comment]
This issue is fixed - Japanese newsroom page is fixed now - 
https://issue245-newsroom--sunstar--hlxsites.hlx.page/jp/_drafts/meet/newsroom

Limiting the description to its first Japanese line. When searched on web - The Japanese full stop is a cute small circle, “。“, placed like the English “.” after a word. You can see that a little space is indeed already included. Hence leveraged - const firstJpLine = result[fieldName].split('。')[0];
            div.textContent = firstJpLine;  

Pl check & validate further - https://github.com/hlxsites/sunstar/pull/296. 

Many Thanks

**Comment by meejain** [comment]
<img width="1120" alt="image" src="https://github.com/hlxsites/sunstar/assets/37831850/9c7db5e6-8634-4b0c-9cfe-a4145b3135b3">
