### ISSUE TITLE
Extra variant for column block

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#447]
Can you please create a variant for the column block where we could have 1 button followed by links like we have on the about us page?

![image](https://github.com/hlxsites/sunstar/assets/1226479/48661777-49db-4b5a-bb7b-d95d13b586b0)
https://www.sunstar.com/about/
![image](https://github.com/hlxsites/sunstar/assets/1226479/d14b4912-5d45-4298-bb6f-0e196cf15e56)

![image](https://github.com/hlxsites/sunstar/assets/1226479/05f5768f-a68d-44f9-a327-d99216bd67ed)

**Comment by shrotia** [comment]
@ehrro I have created a new variant of Link Block to achieve this. 
<img width="644" alt="image" src="https://github.com/hlxsites/sunstar/assets/119420493/887d96ee-24eb-4762-aa5c-76cb001ca977">

Please have a look: PR: https://github.com/hlxsites/sunstar/pull/467
Sample Page URL: https://issue-447--sunstar--hlxsites.hlx.page/_drafts/shroti/about

If it looks good, I can update the main About page and update the Document Library.

Or otherwise I can delve further into the Column Block to address this variation. Please provide your thoughts on this.

**Comment by ehrro** [comment]
Hello @shrotia 

I am good with this approach.

There are some problems:

1. No-margin is applied to all elements inside the columns block. it should only target the columns container
![image](https://github.com/hlxsites/sunstar/assets/1226479/0c85d817-0a2f-4b3f-843b-2987059390ce)

2. Make sure to add correct arrows, some space between the links (you can apply 1 rem to the span arrow element) and align the arrows to the center (maybe display in flex and items-center) 
![image](https://github.com/hlxsites/sunstar/assets/1226479/8a88bf2a-9533-477d-b566-45a453cbbcbe)

3. Make sure it works fine on the mobile (maybe flex-wrap if needed and margin-top and bottom to leave some space between buttons)

Thank you :)

**Comment by shrotia** [comment]
@ehrro I went with a relatively simple change. PR: https://github.com/hlxsites/sunstar/pull/477

Here is the latest working copy: https://issue-447-v2--sunstar--hlxsites.hlx.page/_drafts/shroti/about

<img width="577" alt="image" src="https://github.com/hlxsites/sunstar/assets/119420493/9539c43f-7b49-48a3-90cf-33665422770a">
