### ISSUE TITLE
history page

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#450]
1 .The space between images is to big.

It seems that all the div elements have padding top and bottom that creates a big space.

![image](https://github.com/hlxsites/sunstar/assets/1226479/36265493-f215-4593-806a-f58e6568f3f9)

Can you please remove the space?

2. The light gray section has left and right padding that affect the container size.
![image](https://github.com/hlxsites/sunstar/assets/1226479/15cc3f95-538c-4250-899d-a8f88175583d)

@dnbute

**Comment by dnbute** [comment]
@ehrro For the second point, I added the padding because without it, the text reaches the edges of the coloured section and it looks weird to me
<img width="541" alt="Screenshot 2023-11-28 at 09 47 32" src="https://github.com/hlxsites/sunstar/assets/44490413/480ba254-130b-4e0b-b706-3357dd18c529">

I can of course remove it, but I think we still want the padding on top and at the bottom
Let me know what you think
