### ISSUE TITLE
Japanese search > search excerpt/snippet too long

### ISSUE THREAD

**Issue by ehrro** [hlxsites/sunstar#537]
![image](https://github.com/hlxsites/sunstar/assets/1226479/25b526ce-82b1-46e9-ae6e-be9ca1e69bc4)
https://main--sunstar--sunstar-global.hlx.page/jp/search?s=%E5%BE%93%E4%BA%8B%E8%80%85

@sdmcraft

**Comment by dnbute** [comment]
@meejain has more expertise for this but I believe the problem is that the Japanese pages have really long descriptions, if we could trim them down then this will no longer happen, the alternative is to crop the text at the first `。` like we do in some other places, but this would mean that we might have some search query matches in the full description, that won't show up in the cropped one that we display here, is it a requirement to show the matches in bold for the search result like here?
<img width="92" alt="Screenshot 2023-12-12 at 15 16 47" src="https://github.com/hlxsites/sunstar/assets/44490413/0f45f67b-510c-43bf-bb90-7b7a65b981ed">

**Comment by meejain** [comment]
Yes, let me work on this one as we applied the same logic for https://main--sunstar--hlxsites.hlx.page/jp/newsroom, as well.
